export const majorLanguages = [
    'English',
    'Mandarin Chinese',
    'Spanish',
    'Hindi',
    'Arabic',
    'Bengali',
    'Portuguese',
    'Russian',
    'Urdu',
    'Indonesian',
    'French',
    'German',
    'Japanese',
    'Swahili',
    'Turkish',
    'Korean',
    'Italian',
    'Telugu',
    'Vietnamese',
    'Tamil',
  ];