export const groupReviewsList = [
    {
        guestName: 'Alice Johnson',
        reservationId: 'R789f012',
        reviewDate: '2023-02-05',
        propertyName: 'Mountain View Lodge',
        overallRating: '9.2',
        comments:null,
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '8' },
            { category: 'Location', rating: '9' },
            { category: 'Comfort', rating: '10' },
            { category: 'Value for money', rating: '8' },
            { category: 'Cleanliness', rating: '9' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Bob Smith',
        reservationId: 'R345d678',
        reviewDate: '2023-03-12',
        propertyName: 'Seaside Retreat',
        overallRating: '8.5',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '7' },
            { category: 'Location', rating: '8' },
            { category: 'Comfort', rating: '9' },
            { category: 'Value for money', rating: '7' },
            { category: 'Cleanliness', rating: '8' },
            { category: 'Facilities', rating: '8' },
        ]
    },
    {
        guestName: 'Charlie Brown',
        reservationId: 'R90d1234',
        reviewDate: '2023-04-08',
        propertyName: 'Cozy Cabin',
        overallRating: '8.8',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '9' },
            { category: 'Location', rating: '8' },
            { category: 'Comfort', rating: '9' },
            { category: 'Value for money', rating: '7' },
            { category: 'Cleanliness', rating: '8' },
            { category: 'Facilities', rating: '8' },
        ]
    },
    {
        guestName: 'David Miller',
        reservationId: 'R56r890',
        reviewDate: '2023-05-20',
        propertyName: 'Cityscape Apartments',
        overallRating: '9.5',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '10' },
            { category: 'Location', rating: '9' },
            { category: 'Comfort', rating: '10' },
            { category: 'Value for money', rating: '9' },
            { category: 'Cleanliness', rating: '10' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Eva Davis',
        reservationId: 'R234r567',
        reviewDate: '2023-06-10',
        propertyName: 'Lakeside Retreat',
        overallRating: '9.0',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '9' },
            { category: 'Location', rating: '8' },
            { category: 'Comfort', rating: '10' },
            { category: 'Value for money', rating: '8' },
            { category: 'Cleanliness', rating: '9' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Frank White',
        reservationId: 'R6748w901',
        reviewDate: '2023-07-15',
        propertyName: 'Serene Heights',
        overallRating: '8.2',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '8' },
            { category: 'Location', rating: '7' },
            { category: 'Comfort', rating: '8' },
            { category: 'Value for money', rating: '7' },
            { category: 'Cleanliness', rating: '8' },
            { category: 'Facilities', rating: '8' },
        ]
    },

    {
        guestName: 'Grace Taylor',
        reservationId: 'R3456f78',
        reviewDate: '2023-08-22',
        propertyName: 'Tranquil Haven',
        overallRating: '9.8',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '10' },
            { category: 'Location', rating: '9' },
            { category: 'Comfort', rating: '10' },
            { category: 'Value for money', rating: '9' },
            { category: 'Cleanliness', rating: '10' },
            { category: 'Facilities', rating: '10' },
        ]
    },
    {
        guestName: 'Harry Anderson',
        reservationId: 'R012f345',
        reviewDate: '2023-09-18',
        propertyName: 'Garden Retreat',
        overallRating: '8.5',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:null,
        reviewCategories: [
            { category: 'Staff', rating: '9' },
            { category: 'Location', rating: '8' },
            { category: 'Comfort', rating: '9' },
            { category: 'Value for money', rating: '7' },
            { category: 'Cleanliness', rating: '8' },
            { category: 'Facilities', rating: '8' },
        ]
    },
    {
        guestName: 'Isabel Martinez',
        reservationId: 'R234w567',
        reviewDate: '2023-10-10',
        propertyName: 'Skyline Apartments',
        overallRating: '9.4',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '9' },
            { category: 'Location', rating: '10' },
            { category: 'Comfort', rating: '9' },
            { category: 'Value for money', rating: '8' },
            { category: 'Cleanliness', rating: '10' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Jackie Brown',
        reservationId: 'R6f78901',
        reviewDate: '2023-11-15',
        propertyName: 'Harbor View Villa',
        overallRating: '8.7',
        comments:null,
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '8' },
            { category: 'Location', rating: '7' },
            { category: 'Comfort', rating: '8' },
            { category: 'Value for money', rating: '7' },
            { category: 'Cleanliness', rating: '8' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Katherine Lee',
        reservationId: 'R7890fg12',
        reviewDate: '2023-12-05',
        propertyName: 'Riverside Retreat',
        overallRating: '9.6',
        comments:null,
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '10' },
            { category: 'Location', rating: '9' },
            { category: 'Comfort', rating: '10' },
            { category: 'Value for money', rating: '9' },
            { category: 'Cleanliness', rating: '10' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Liam Johnson',
        reservationId: 'R012cw345',
        reviewDate: '2024-01-08',
        propertyName: 'Golden Sands Resort',
        overallRating: '8.9',
        comments:null,
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '9' },
            { category: 'Location', rating: '8' },
            { category: 'Comfort', rating: '9' },
            { category: 'Value for money', rating: '8' },
            { category: 'Cleanliness', rating: '9' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Mia Garcia',
        reservationId: 'R23c4567',
        reviewDate: '2024-02-20',
        propertyName: 'Elegant Escape',
        overallRating: '9.1',
        comments:null,
        replies: null,
        reviewCategories: [
            { category: 'Staff', rating: '9' },
            { category: 'Location', rating: '8' },
            { category: 'Comfort', rating: '9' },
            { category: 'Value for money', rating: '8' },
            { category: 'Cleanliness', rating: '9' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Noah Rodriguez',
        reservationId: 'R678w901',
        reviewDate: '2024-03-15',
        propertyName: 'Luxury Haven',
        overallRating: '8.3',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '8' },
            { category: 'Location', rating: '7' },
            { category: 'Comfort', rating: '8' },
            { category: 'Value for money', rating: '7' },
            { category: 'Cleanliness', rating: '8' },
            { category: 'Facilities', rating: '8' },
        ]
    },
    {
        guestName: 'Olivia Adams',
        reservationId: 'R789y012',
        reviewDate: '2024-04-08',
        propertyName: 'Peaceful Cottage',
        overallRating: '9.7',
        comments:null,
        replies:'Welcome.',
        reviewCategories: [
            { category: 'Staff', rating: '10' },
            { category: 'Location', rating: '9' },
            { category: 'Comfort', rating: '10' },
            { category: 'Value for money', rating: '9' },
            { category: 'Cleanliness', rating: '10' },
            { category: 'Facilities', rating: '9' },
        ]
    },
    {
        guestName: 'Logan Wright',
        reservationId: 'R0125345',
        reviewDate: '2024-05-15',
        propertyName: 'Serenity Retreat',
        overallRating: '8.6',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies: null,
        reviewCategories: [
            { category: 'Staff', rating: '9' },
            { category: 'Location', rating: '8' },
            { category: 'Comfort', rating: '9' },
            { category: 'Value for money', rating: '8' },
            { category: 'Cleanliness', rating: '9' },
            { category: 'Facilities', rating: '8' },
        ]
    },
    {
        guestName: 'Sophia Miller',
        reservationId: 'R23r4567',
        reviewDate: '2024-06-10',
        propertyName: 'Tranquil Oasis',
        overallRating: '9.3',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies: null,
        reviewCategories: [
          { category: 'Staff', rating: '9' },
          { category: 'Location', rating: '8' },
          { category: 'Comfort', rating: '9' },
          { category: 'Value for money', rating: '8' },
          { category: 'Cleanliness', rating: '9' },
          { category: 'Facilities', rating: '9' },
        ]
      },
      {
        guestName: 'Jackson Davis',
        reservationId: 'R67f8901',
        reviewDate: '2024-07-15',
        propertyName: 'Mountain Hideaway',
        overallRating: '8.9',
        comments:null,
        replies: null,
        reviewCategories: [
          { category: 'Staff', rating: '8' },
          { category: 'Location', rating: '7' },
          { category: 'Comfort', rating: '8' },
          { category: 'Value for money', rating: '7' },
          { category: 'Cleanliness', rating: '8' },
          { category: 'Facilities', rating: '8' },
        ]
      },
      {
        guestName: 'Aiden Wilson',
        reservationId: 'R89e0123',
        reviewDate: '2024-08-22',
        propertyName: 'Sunrise Villa',
        overallRating: '9.5',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies:'Welcome.',
        reviewCategories: [
          { category: 'Staff', rating: '9' },
          { category: 'Location', rating: '10' },
          { category: 'Comfort', rating: '9' },
          { category: 'Value for money', rating: '8' },
          { category: 'Cleanliness', rating: '10' },
          { category: 'Facilities', rating: '9' },
        ]
      },
      {
        guestName: 'Emma Brown',
        reservationId: 'R012h345',
        reviewDate: '2024-09-18',
        propertyName: 'Rustic Retreat',
        overallRating: '8.7',
        comments:'I really enjoyed My stay and would recommend the stay to anyone.',
        replies: null,
        reviewCategories: [
          { category: 'Staff', rating: '8' },
          { category: 'Location', rating: '7' },
          { category: 'Comfort', rating: '8' },
          { category: 'Value for money', rating: '7' },
          { category: 'Cleanliness', rating: '8' },
          { category: 'Facilities', rating: '8' },
        ]
      },
];
